import random

#Declarating of counters and accumulators for visibility

count_p, count_n, count_o, count_even, count_odd, count_prime = 0,0,0,0,0,0
sum_p, sum_n, sum_o = 0, 0, 0
list_data=[]
total_numbers=100

#Evaluating if values generated by random are positive, negative or zero
for item in range(total_numbers):
    value=random.randint(-100,100)
    list_data.append(value)
    if value>0:
        count_p+=1
        sum_p+=value
    elif value<0:
        count_n+=1
        sum_n+=value
    else:
        count_o+=1
        sum_o+=value

#Processing the list to evaluate if his values are odd or even
for data in list_data:
    if data%2==0:
        count_even+=1
    else:
        count_odd+=1
        
#Finlally printing the results
print("*-"*15)
print("Total numbers: %s" % total_numbers)
print("*"*30)
print("Total positive numbers: %s" % count_p)
print("Total negative numbers: %s" % count_n)
print("Total zero values: %s" % count_o)
print("="*30)
print("Total even number: %s" % count_even)
print("Total odd number: %s" % count_odd)
print("="*30)
print("Rate of positive numbers: %0.2f" % float(count_p/len(list_data)))
print("Rate of negative numbers: %0.2f" % float(count_n/len(list_data)))
print("Rate of zero numbers: %0.2f" % float(count_o/len(list_data)))
print("*-"*15)




